baseURL: https://jordimon.netlify.app/
languageCode: en-GB
title: Jordi Mon's personal site
theme: hugo-split-theme
disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap
googleAnalytics: ''
copyright: '&copy;2021 Jordi Mon Companys'
params:
  author: Jordi Mon Companys
  description: Find everything related to Product Specialist Jordi Mon. Social Media handles, blog...
#  favicon: favicon.ico
  links:
    - list1:
        heading: Read
        link:
          - text: Blog
            url: 'blog.mon.company'
#          - text: Email
#            url: '#'
#          - text: Newsletter
#            url: '#'
    - list2:
        heading: Social
        link:
          - text: Twitter
            url: 'https://www.twitter.com/jordimonpmm'
          - text: LinkedIn
            url: 'https://www.linkedin.com/in/jordimoncompanys'
#          - text: Dribbble
#            url: '#'
#    - list3:
#        heading: Network
#        link:
#          - text: Link One
#            url: '#'
#          - text: Link Two
#            url: '#'
#          - text: Link Three
#            url: '#'
  shareImage: images/social.jpg
  twitterHandle: jordimonpmm
  visual:
    image:
      enable: yes
      file: images/JordiMon.jpeg
      position: center center
    video:
      enable: no 
      file: videos/background.mp4
      mute: yes
